In [3]:
from collections import OrderedDict
import pickle
import numpy as np
import operator

In [4]:
filters=open('filters.txt','r').readline().strip().split('|')
file="pipeFormat.csv"
f=open(file,"r")
headers=f.readline().strip().split('|')
f.close()

def getIndex(s):
    return headers.index(s)

def dumpPickle(name,data):
    pickle.dump(data,open('pickles/{}.pickle'.format(name),'wb'))
    
def loadPickle(name):
    return pickle.load(open('pickles/{}.pickle'.format(name),'rb'))
    

In [12]:
def getDetails(filterby):
    data={}
    file="pipeFormat.csv"
    noLabel=['.','']
    f=open(file,"r")
    headers=f.readline().strip().split('|')
   
    nagid={}
    targets={}
    yearIndex=getIndex('year')
    nagcodeIndex=getIndex('nagcode_1')
    nagnameIndex=getIndex('nag_name')
    BRD2Index=getIndex(filterby)

    for l in f:
        row=l.split("|")
        year=int(row[yearIndex])
        nagcode=int(row[nagcodeIndex])
        nagname=row[nagnameIndex]
        brd = row[BRD2Index]
        if nagcode not in data:
            data[nagcode]=0
        if brd!='':
            if len(brd.split('/'))>1:
                brd = brd.split('/')[-1]
                brd = '19'+brd if 45<=int(brd)<=99 else '20'+brd
            else:
                brd = brd.split('-')[0]
        data[nagcode] = brd
    f.close()
    return data


def getDetails2(filterby):
    data={}
    file="pipeFormat.csv"
    noLabel=['.','']
    f=open(file,"r")
    headers=f.readline().strip().split('|')
   
    nagid={}
    targets={}
    yearIndex=getIndex('year')
    nagcodeIndex=getIndex('nagcode_1')
    nagnameIndex=getIndex('nag_name')
    BRD2Index=getIndex(filterby)
    notFound = set()

    for l in f:
        row=l.split("|")
        year=int(row[yearIndex])
        nagcode=int(row[nagcodeIndex])
        nagname=row[nagnameIndex]
        brd = row[BRD2Index]
        if nagcode not in data:
            if brd!='':
                if len(brd.split('/'))>1:
                    brd = brd.split('/')[-1]
                    brd = '19'+brd if 45<=int(brd)<=99 else '20'+brd
                else:
                    brd = brd.split('-')[0]
                temp = int(brd) - int(year)
                if temp>=0:
                    data[nagcode] = temp
                else:
                    notFound.add(nagcode)
    f.close()
    print(notFound)
    return data

In [6]:
data = getDetails('startdate2')

yearDied = loadPickle('yearDied')
Deadyear={}
for year in yearDied:
    for nagcode in yearDied[year]: 
        if nagcode not in Deadyear:
            Deadyear[nagcode]=year
        else:
            print(nagcode,year)
            
thirivedAfterBRD={}
for nagcode in Deadyear:
    if data[nagcode]!='':
        temp =Deadyear[nagcode] - int(data[nagcode])
        if temp>=0:
            thirivedAfterBRD[nagcode] = Deadyear[nagcode] - int(data[nagcode])

yearLength = loadPickle('yearLength')
x,y = [],[]
for nagcode in thirivedAfterBRD:
    x.append(thirivedAfterBRD[nagcode])
    y.append(yearLength[nagcode]) 
    
np.corrcoef(x,y)

array([[ 1.        ,  0.79837058],
       [ 0.79837058,  1.        ]])

In [18]:
data = getDetails('startdate2')

yearDied = loadPickle('yearDied')
Deadyear={}
for year in yearDied:
    for nagcode in yearDied[year]: 
        if nagcode not in Deadyear:
            Deadyear[nagcode]=year
        else:
            print(nagcode,year)
            
thirivedAfterBRD={}
for nagcode in Deadyear:
    if data[nagcode]!='':
        temp =Deadyear[nagcode] - int(data[nagcode])
        if temp>=0:
            thirivedAfterBRD[nagcode] = Deadyear[nagcode] - int(data[nagcode])

yearLength = loadPickle('yearLength')
x,y = [],[]
for nagcode in thirivedAfterBRD:
    x.append(thirivedAfterBRD[nagcode])
    y.append(yearLength[nagcode]) 
    
np.corrcoef(x,y)

array([[ 1.        ,  0.79837058],
       [ 0.79837058,  1.        ]])

In [19]:
data = getDetails2('startdate1')

yearLength = loadPickle('yearLength')
x,y = [],[]
for nagcode in set(yearLength) & set(data):
    x.append(data[nagcode])
    y.append(yearLength[nagcode]) 
    
np.corrcoef(x,y)

{36, 484, 10, 75, 333, 339, 349}


array([[ 1.        ,  0.26119345],
       [ 0.26119345,  1.        ]])

In [26]:
dumpPickle('BRD_NAG',data)

In [22]:
dumpPickle('deadYear',Deadyear)

In [45]:
import networkx as nx

In [48]:
nx.closeness?

In [14]:
{1,4}&{4,6}

{4}

In [25]:
data

{1: 1,
 2: 1,
 3: 0,
 4: 0,
 5: 1,
 6: 0,
 7: 94,
 8: 0,
 9: 1,
 11: 1,
 12: 99,
 13: 0,
 14: 0,
 15: 0,
 16: 96,
 17: 1,
 18: 0,
 19: 3,
 20: 2,
 21: 19,
 22: 3,
 23: 2,
 24: 2,
 25: 2,
 26: 2,
 27: 5,
 28: 9,
 29: 1,
 30: 0,
 31: 1,
 32: 0,
 33: 0,
 34: 7,
 35: 23,
 37: 3,
 38: 0,
 39: 0,
 40: 3,
 41: 0,
 42: 0,
 46: 3,
 47: 5,
 48: 8,
 49: 8,
 50: 2,
 52: 1,
 54: 0,
 55: 0,
 56: 0,
 57: 21,
 58: 5,
 59: 0,
 60: 0,
 61: 0,
 62: 1,
 63: 8,
 64: 2,
 65: 6,
 66: 0,
 67: 0,
 68: 0,
 69: 0,
 70: 0,
 71: 0,
 72: 0,
 73: 1,
 74: 0,
 77: 0,
 78: 6,
 79: 0,
 80: 9,
 82: 1,
 83: 0,
 84: 9,
 86: 0,
 87: 0,
 88: 0,
 89: 0,
 90: 1,
 91: 0,
 92: 2,
 93: 0,
 94: 0,
 95: 0,
 96: 0,
 97: 0,
 98: 10,
 99: 0,
 100: 0,
 101: 15,
 102: 1,
 103: 2,
 104: 0,
 105: 9,
 106: 1,
 107: 0,
 108: 5,
 109: 0,
 110: 34,
 111: 0,
 112: 0,
 113: 0,
 114: 1,
 115: 2,
 116: 0,
 117: 6,
 118: 2,
 119: 0,
 120: 0,
 121: 0,
 122: 4,
 123: 1,
 124: 1,
 125: 2,
 126: 2,
 127: 2,
 128: 2,
 129: 1,
 130: 1,
 131: 13,
 132: 5